apiVersion: v1
kind: Secret
metadata:
  name: azure-creds
  namespace: openshift-config
  labels:
    cluster.open-cluster-management.io/type: azr
    cluster.open-cluster-management.io/credentials: ""
stringData:
  cloudName: AzurePublicCloud
  ssh-privatekey: |
    # Put SSH Private Key Block Here
  httpsProxy: ''
  httpProxy: ''
  baseDomainResourceGroupName: acme-rg
  noProxy: ''
  ssh-publickey: |
    ssh-ed25519 AAAAABBBBBCCCCCDDDDD12345123451234512345EEEEEFFFFFGGGGGHHHHH1234512345 dtrieu@acme.com
  additionalTrustBundle: ''
  pullSecret: |
    {"auths":{"cloud.openshift.com":{"auth":"ABCDE12345...","email":"dtrieu@acme.com"},"quay.io":{"auth":"ABCDE12345...","email":"dtrieu@acme.com"},"registry.connect.redhat.com":{"auth":"ABCDE12345...","email":"dtrieu@acme.com"},"registry.redhat.io":{"auth":"ABCDE12345...","email":"dtrieu@acme.com"}}}
  baseDomain: acme.azure.microsoft.com
  osServicePrincipal.json: |
    {"clientId":"abcde-12345-abcde-12345-abcde12345","clientSecret":"ABCDE","tenantId":"abcde-12345-abcde-12345-abcde12345","subscriptionId":"abcde-12345-abcde-12345-abcde12345"}
type: Opaque
