kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:subscription-admin-0'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:subscription-admin'
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kube:admin
