apiVersion: v1
kind: Secret
metadata:
  name: import-cluster-01
  namespace: openshift-config
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          server: https://api.nsvvuera.eastus.aroapp.io:6443
        name: api-nsvvuera-eastus-aroapp-io:6443
    contexts:
      - context:
          cluster: api-nsvvuera-eastus-aroapp-io:6443
          namespace: default
          user: kubeadmin/api-nsvvuera-eastus-aroapp-io:6443
        name: default/api-nsvvuera-eastus-aroapp-io:6443/kube:admin
    current-context: default/api-nsvvuera-eastus-aroapp-io:6443/kube:admin
    preferences: {}
    users:
      - name: kubeadmin/api-nsvvuera-eastus-aroapp-io:6443
        user:
          token: sha256~T0yevYU7r7mqr-6LPHAbMGsTUATIXQGyiX3Hfm5olTI
type: Opaque
