apiVersion: v1
kind: Secret
metadata:
  name: import-cluster-01
  namespace: openshift-config
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          server: https://api.hv2xch5g.eastus.aroapp.io:6443
        name: api-hv2xch5g-eastus-aroapp-io:6443
    contexts:
      - context:
          cluster: api-hv2xch5g-eastus-aroapp-io:6443
          namespace: default
          user: kubeadmin/api-hv2xch5g-eastus-aroapp-io:6443
        name: default/api-hv2xch5g-eastus-aroapp-io:6443/kube:admin
    current-context: default/api-hv2xch5g-eastus-aroapp-io:6443/kube:admin
    preferences: {}
    users:
      - name: kubeadmin/api-hv2xch5g-eastus-aroapp-io:6443
        user:
          token: sha256~gXDmmd9Yjjg2MFrYT28fosKeW5aFdvCt0rs4-FffO2k
type: Opaque
