#!/bin/bash

# Generates the auto-import-secret/kubeconfig from the current-context.
# ./create-auto-import-secret import-clustername username password api-url

USER_NAME=$2
USER_PASS=$3
API=$4

oc login -u ${USER_NAME-replaceuser} -p ${USER_PASS-replacepassword} --server ${API-replacementapi}

CURRENT_CONTEXT=$(oc config current-context)
CLUSTER_NAME=$(oc config view --raw -o=go-template='{{range .contexts}}{{if eq .name "'''${CURRENT_CONTEXT}'''"}}{{ index .context "cluster" }}{{end}}{{end}}')
CLUSTER_NAMESPACE=$(oc config view --raw -o=go-template='{{range .contexts}}{{if eq .name "'''${CURRENT_CONTEXT}'''"}}{{ index .context "namespace" }}{{end}}{{end}}')
CLUSTER_ENDPOINT=$(oc config view --raw -o=go-template='{{range .clusters}}{{if eq .name "'''${CLUSTER_NAME}'''"}}{{ .cluster.server }}{{end}}{{ end }}')
CLUSTER_OAUTH_ENDPOINT=$(oc get route -n openshift-authentication -o jsonpath='{.items[].spec.host}{"\n"}')
USER_TOKEN=$(oc whoami -t)

cat <<EOF > auto-import-secret-${1-replaceclustername}.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ${1-replaceclustername}
  namespace: openshift-config
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          server: ${CLUSTER_ENDPOINT}
        name: ${CLUSTER_NAME}
    contexts:
      - context:
          cluster: ${CLUSTER_NAME}
          namespace: ${CLUSTER_NAMESPACE}
          user: ${USER_NAME}/${CLUSTER_NAME}
        name: ${CURRENT_CONTEXT}
    current-context: ${CURRENT_CONTEXT}
    preferences: {}
    users:
      - name: ${USER_NAME}/${CLUSTER_NAME}
        user:
          token: ${USER_TOKEN}
type: Opaque
EOF

echo ""
echo ""
echo "Secret auto-import-secret-${1-replaceclustername}.yaml generated."
echo "Next step: Apply the generated secret to hub."
echo "$ oc login <hub>"
echo "$ oc apply -f auto-import-secret-${1-replaceclustername}.yaml"
