#!/bin/bash

AZURE_SUBSCRIPTION_ID=
AZURE_TENANT_ID=
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
AZURE_RESOURCE_GROUP=
AZURE_STORAGE_ACCOUNT=
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=
AZURE_STORAGE_ENDPOINT=blob.core.windows.net
AZURE_STORAGE_CONTAINER=
AZURE_CLOUD_NAME=AzurePublicCloud

cat <<EOF > oadp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: oadp-secret
  namespace: openshift-config
  labels:
    cluster.open-cluster-management.io/backup: ""
stringData:
  azureSubscriptionId: ${AZURE_SUBSCRIPTION_ID}
  azureTenantId: ${AZURE_TENANT_ID}
  azureClientId: ${AZURE_CLIENT_ID}
  azureClientSecret: ${AZURE_CLIENT_SECRET}
  azureResourceGroup: ${AZURE_RESOURCE_GROUP}
  azureStorageAccount: ${AZURE_STORAGE_ACCOUNT}
  azureStorageAccountAccessKey: ${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
  azureStorageEndpoint: ${AZURE_STORAGE_ENDPOINT}
  azureStorageContainer: ${AZURE_STORAGE_CONTAINER}
  azureCloudName: ${AZURE_CLOUD_NAME}
EOF


cat <<EOF > credentials-velero
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_TENANT_ID=${AZURE_TENANT_ID}
AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
AZURE_CLOUD_NAME=${AZURE_CLOUD_NAME}
EOF

cat <<EOF > redhat-oadp-acm-dpa.yaml
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: acm-dpa
  namespace: open-cluster-management-backup
spec:
  configuration:
    velero:
      defaultPlugins:
        - azure
        - openshift
      resourceTimeout: 10m
    restic:
      enable: true
  backupLocations:
    - velero:
        config:
          resourceGroup: ${AZURE_RESOURCE_GROUP}
          storageAccount: ${AZURE_STORAGE_ACCOUNT}
          subscriptionId: ${AZURE_SUBSCRIPTION_ID}
          storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
        credential:
          key: cloud
          name: cloud-credentials-azure
        provider: azure
        default: true
        objectStorage:
          bucket: ${AZURE_STORAGE_CONTAINER}
          prefix: acm
  snapshotLocations: 
    - velero:
        config:
          resourceGroup: ${AZURE_RESOURCE_GROUP}
          subscriptionId: ${AZURE_SUBSCRIPTION_ID}
          incremental: "true"
        name: default
        provider: azure
EOF

echo "$ oc create secret generic cloud-credentials-azure --namespace open-cluster-management-backup --from-file cloud=./credentials-velero"
echo "$ oc apply -f redhat-oadp-acm-dpa.yaml"