apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: AZURE
    config:
      storage_account:
      storage_account_key:
      container:
      endpoint: blob.core.windows.net 
      max_retries: 0
