apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: versedt-ca-bundle
    namespace: openshift-config
    files:
      - ca-bundle.crt=versedt-ca.crt
