apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-azure-pool1 # Update: pl-<clusterPoolName>
  annotations:
    policy.open-cluster-management.io/description: 'Deploy clusterpool azure-pool1' # Update: Deploy clusterpool <clusterPoolName>
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: azure-pool1-argoapp # Update: <clusterName>-argoapp
        spec:
          remediationAction: enforce
          severity: low
          pruneObjectBehavior: DeleteAll
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: azure-pool1 # Update: <clusterName>
                  namespace: openshift-gitops
                  finalizers:
                  - resources-finalizer.argocd.argoproj.io
                spec:
                  destination:
                    server: 'https://kubernetes.default.svc'
                  project: default
                  source:
                    path: managed-clusters/azure-pool # Update: <provider>
                    repoURL: 'https://github.com/dtrieu80/acm-bootstrap.git'
                    targetRevision: main
                    helm:
                      # Update: Refer to Helm Chart for proper values
                      values: |
                        clusterPoolName: azure-pool1
                        poolSize: 2
                        poolAwake: 0
                        install:
                          ocpVersion: 4.12.35
                          region: eastus
                          baseDomain: {{ fromSecret "openshift-config" "demo-creds" "baseDomain" | base64dec }}
                          resourceGroup: {{ fromSecret "openshift-config" "demo-creds" "baseDomainResourceGroupName" | base64dec }}
                          controlPlaneReplicas: 3
                          controlPlane:
                            size: Standard_D4s_v3
                            osDiskSizeGB: 128
                          computeReplicas: 2
                          compute:
                            size: Standard_D2s_v3
                            osDiskSizeGB: 128
                            zones:
                            - "1"
                            - "2"
                            - "3"
                          sshPubkey: {{ fromSecret "openshift-config" "demo-creds" "ssh-publickey" | base64dec }}
      extraDependencies:
      - apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        name: azure-pool1-namespace # Update: <clusterName>-namespace
        namespace: ""
        compliance: Compliant
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: azure-pool1-namespace # Update: <clusterName>-namespace
        spec:
          remediationAction: enforce
          severity: low
          pruneObjectBehavior: DeleteAll
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: azure-pool1 # Update: <clusterName>
