apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-hive-secrets
  annotations:
    policy.open-cluster-management.io/description: 'Populate Hive Secrets'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-hive-azure-secrets
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: azure-creds
                  namespace: openshift-config
            {{- range $cd := (lookup "hive.openshift.io/v1" "ClusterDeployment" "" "").items }}
              {{- if (eq $cd.metadata.labels.cloud "Azure") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-azure-creds
                  namespace: {{ $cd.metadata.name }}
                data:
                  osServicePrincipal.json: {{ fromSecret "openshift-config" "azure-creds" "osServicePrincipal.json" }}
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-pull-secret
                  namespace: {{ $cd.metadata.name }}
                data:
                  .dockerconfigjson: {{ fromSecret "openshift-config" "azure-creds" "pullSecret" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-ssh-private-key
                  namespace: {{ $cd.metadata.name }}
                data:
                  ssh-privatekey: {{ fromSecret "openshift-config" "azure-creds" "ssh-privatekey" }}
                type: Opaque
              {{- end }}
              {{- if and (eq $cd.metadata.name "glqpr")
                         (eq $cd.metadata.labels.cloud "vSphere") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-vsphere-creds
                  namespace: {{ $cd.metadata.name }}
                data:
                  username: {{ fromSecret "openshift-config" "vsphere-creds" "username" }} 
                  password: {{ fromSecret "openshift-config" "vsphere-creds" "password" }} 
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-vsphere-certs
                  namespace: {{ $cd.metadata.name }}
                data:
                  .cacert: {{ fromSecret "openshift-config" "vsphere-creds" "cacertificate" }} 
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-pull-secret
                  namespace: {{ $cd.metadata.name }}
                data:
                  .dockerconfigjson: {{ fromSecret "openshift-config" "vsphere-creds" "pullSecret" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-ssh-private-key
                  namespace: {{ $cd.metadata.name }}
                data:
                  ssh-privatekey: {{ fromSecret "openshift-config" "vsphere-creds" "ssh-privatekey" }}
                type: Opaque
              {{- end }}
              {{- if and (eq $cd.metadata.name "5tktf")
                         (eq $cd.metadata.labels.cloud "vSphere") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-vsphere-creds
                  namespace: {{ $cd.metadata.name }}
                data:
                  username: {{ fromSecret "openshift-config" "vmware2-creds" "username" }} 
                  password: {{ fromSecret "openshift-config" "vmware2-creds" "password" }} 
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-vsphere-certs
                  namespace: {{ $cd.metadata.name }}
                data:
                  .cacert: {{ fromSecret "openshift-config" "vmware2-creds" "cacertificate" }} 
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-pull-secret
                  namespace: {{ $cd.metadata.name }}
                data:
                  .dockerconfigjson: {{ fromSecret "openshift-config" "vmware2-creds" "pullSecret" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cd.metadata.name }}-ssh-private-key
                  namespace: {{ $cd.metadata.name }}
                data:
                  ssh-privatekey: {{ fromSecret "openshift-config" "vmware2-creds" "ssh-privatekey" }}
                type: Opaque
              {{- end }}
            {{- end }}
