apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-hive-pool-secrets
  annotations:
    policy.open-cluster-management.io/description: 'Populate Hive Pool Secrets'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-hive-pool-azure-secrets
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: demo-creds
                  namespace: openshift-config
            {{- range $cp := (lookup "hive.openshift.io/v1" "ClusterPool" "" "").items }}
              {{- if (eq $cp.metadata.labels.cloud "Azure") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cp.metadata.name }}-pull-secret
                  namespace: {{ $cp.metadata.name }}
                data:
                  .dockerconfigjson: {{ fromSecret "openshift-config" "vmware-demo-creds" "pullSecret" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $cp.metadata.name }}-azure-creds
                  namespace: {{ $cp.metadata.name }}
                data:
                  osServicePrincipal.json: {{ fromSecret "openshift-config" "demo-creds" "osServicePrincipal.json" }}
                type: Opaque
              {{- end }}
            {{- end }}
