---
apiVersion: v1
kind: Namespace
metadata:
  name: acm-policies-deployments
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: acm-policies-deployments
spec:
  clusterSet: default
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sub-clusterdeploy-hub1
  namespace: acm-policies-deployments
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: /acm-policies/policysets/clusterdeploy-hub1
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: acm-policies/acm-policies-channel
  placement:
    local: true
