---
apiVersion: v1
kind: Namespace
metadata:
  name: acm-policies-betacorp
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: betacorp
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: betacorp
  namespace: acm-policies
spec:
  clusterSet: betacorp
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: betacorp
  namespace: acm-policies-betacorp
spec:
  clusterSet: betacorp
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sub-clusterconfig-betacorp
  namespace: acm-policies-betacorp
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: /acm-policies/policysets/clusterconfig-betacorp
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: acm-policies/acm-policies-channel
  placement:
    local: true
