---
apiVersion: v1
kind: Namespace
metadata:
  name: acm-policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sub-clusterconfig
  namespace: acm-policies
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: /acm-policies/policysets/clusterconfig
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster