apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-certificates-install
  annotations:
    policy.open-cluster-management.io/description: 'Deploy SSL certificates'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argoapp-certs-install
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: certs-install
                namespace: openshift-gitops
              spec:
                destination:
                  server: 'https://kubernetes.default.svc'
                project: default
                source:
                  path: gitops/clusterconfig/certs-install/overlays/{{hub (index .ManagedClusterLabels "versedt.dev/environment") hub}}
                  repoURL: 'https://github.com/dtrieu80/acm-bootstrap.git'
                  targetRevision: main
                syncPolicy:
                  automated:
                    selfHeal: true