apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-gatekeeper-config
  annotations:
    policy.open-cluster-management.io/description: 'Configure OPA Gatekeeper Operator'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-instance
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.gatekeeper.sh/v1alpha1
                kind: Gatekeeper
                metadata:
                  name: gatekeeper
                spec:
                  audit:
                    auditChunkSize: 500
                    logLevel: INFO
                    replicas: 1
                  validatingWebhook: Enabled
                  mutatingWebhook: Disabled
                  webhook:
                    emitAdmissionEvents: Enabled
                    logLevel: INFO
                    replicas: 2
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-exempt-namespaces
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.gatekeeper.sh/v1alpha1
                kind: Config
                metadata:
                  name: config
                  namespace: openshift-gatekeeper
                spec:
                  match:
                    - excludedNamespaces:
                        - ansible-automation-platform
                        - hive
                        - kube-*
                        - local-quay
                        - multicluster-engine
                        - open-cluster-management
                        - open-cluster-management-*
                        - openshift-*
                        - rhacs-operator
                        - stackrox
                      processes:
                        - '*'
