apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-hive-secrets
  annotations:
    policy.open-cluster-management.io/description: 'Populate Hive Secrets'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-hive-azure-secrets
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            {{- range $mc := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
              {{- if and (ne $mc.metadata.name "local-cluster")
                         (eq (index $mc.metadata.annotations "open-cluster-management/created-via") "hive")
                         (eq $mc.metadata.labels.cloud "Azure") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $mc.metadata.name }}-azure-creds
                  namespace: {{ $mc.metadata.name }}
                data:
                  osServicePrincipal.json: {{ fromSecret "openshift-config" "demo-creds" "osServicePrincipal.json" }}
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $mc.metadata.name }}-pull-secret
                  namespace: {{ $mc.metadata.name }}
                data:
                  .dockerconfigjson: {{ fromSecret "openshift-config" "demo-creds" "pullSecret" }}
                type: kubernetes.io/dockerconfigjson
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $mc.metadata.name }}-ssh-private-key
                  namespace: {{ $mc.metadata.name }}
                data:
                  ssh-privatekey: {{ fromSecret "openshift-config" "demo-creds" "ssh-privatekey" }}
                type: Opaque
              {{- end }}
            {{- end }}
