apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-hive-secrets
  annotations:
    policy.open-cluster-management.io/description: 'Populate Hive Secrets'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-hive-azure-secrets
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            {{- range $mc := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
              {{- if and (ne $mc.metadata.name "local-cluster") (eq $mc.metadata.labels.cloud "Azure") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: test-cm-{{ $mc.metadata.name }}
                  namespace: {{ $mc.metadata.name }}
                data:
                  foo: bar
            - complianceType: musthave
              objectDefinition:
                
              {{- end }}
            {{- end }}
