apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-limit-clusteradmin
  annotations:
    policy.open-cluster-management.io/description: 'Alerts when clusteradmin ClusterRoleBindings more than 2'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: IamPolicy # limit clusteradminrole and report violation
        metadata:
          name: limit-clusteradmin
        spec:
          clusterRole: cluster-admin
          severity: high
          remediationAction: inform # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          maxClusterRoleBindingUsers: 2