apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-oauth-idp
  annotations:
    policy.open-cluster-management.io/description: 'Setup OAuth IDP'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-idp-htpasswd
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                  - htpasswd:
                      fileData:
                        name: htpass-secret
                    mappingMethod: claim
                    name: htpasswd
                    type: HTPasswd
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-htpasswd-secret
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: htpass-secret
                  namespace: openshift-config

