apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-ocp-upgrade
  annotations:
    policy.open-cluster-management.io/description: 'Upgrade OCP to version set in label'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: update-cluster-version
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                spec:
                  channel: stable-{{hub printf("%s.%s", (split "." (index .ManagedClusterLabels "versedt.dev/upgradeTo"))._0, (split "." (index .ManagedClusterLabels "versedt.dev/upgradeTo"))._1) hub}}
                  desiredUpdate:
                    force: true
                    version: {{hub (index .ManagedClusterLabels "versedt.dev/upgradeTo") hub}}
