apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-observability-secrets
  annotations:
    policy.open-cluster-management.io/description: 'Populate Observability Secrets'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-observability-pull-secret
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: multiclusterhub-operator-pull-secret
                  namespace: open-cluster-management-observability
                data:
                  .dockerconfigjson: '{{ fromSecret "openshift-config" "pull-secret" ".dockerconfigjson" }}'
                type: kubernetes.io/dockerconfigjson
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-observability-azurestorage-secret
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: thanos-object-storage
                  namespace: open-cluster-management-observability
                type: Opaque
                data:
                  thanos.yaml: |
                    type: AZURE
                    config:
                      storage_account: {{ fromSecret "openshift-config" "azure-storage-creds" "account" }}
                      storage_account_key: {{ fromSecret "openshift-config" "azure-storage-creds" "accountkey" }}
                      container: {{ fromSecret "openshift-config" "azure-storage-creds" "observabilitycontainer" }}
                      endpoint: blob.core.windows.net
                      max_retries: 0
