apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: pls-clusterconfig
spec:
  description: Cluster Day1 Configuration
  policies:
    - pl-oauth-idp
    - pl-ocp-gitops-install
    - pl-ocp-gitops-config
    - pl-ocp-compliance-install
    - pl-ocp-compliance-cis-scan