apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
  labels:
    cloud: 'Azure'
    region: {{ .Values.install.region }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
  annotations:
    argocd.argoproj.io/sync-options: Delete=true
spec:
  baseDomain: {{ .Values.install.baseDomain }}
  clusterName: {{ .Values.clusterName }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 3
  platform:
    azure:
      baseDomainResourceGroupName: {{ .Values.install.resourcegroup }}
      credentialsSecretRef:
        name: {{ .Values.clusterName }}-azure-creds
      region: {{ .Values.install.region }}
      cloudName: AzurePublicCloud
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.clusterName }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.clusterName }}-ssh-private-key
    imageSetRef:
      name: img{{ .Values.install.ocpVersion }}-multi-appsub
  pullSecretRef:
    name: {{ .Values.clusterName }}-pull-secret