apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.clusterName }}-worker
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  clusterDeploymentRef:
    name: {{ .Values.clusterName }}
  name: worker
  platform:
    azure:
      osDisk:
        diskSizeGB: {{ .Values.runtime.computeOSDiskSizeGB }}
      type: {{ .Values.install.computeSize }}
      zones:
      {{- range .Values.runtime.computeZones }}
      - '{{ . }}'
      {{- end }}
  replicas: {{ .Values.runtime.computeReplicas }}