apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.clusterName }}-worker
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  clusterDeploymentRef:
    name: {{ .Values.clusterName }}
  name: worker
  platform:
    azure:
      osDisk:
        diskSizeGB: {{ .Values.install.compute.osDiskSizeGB }}
      type: {{ .Values.install.compute.size }}
      zones:
      {{- range .Values.install.compute.zones }}
      - '{{ . }}'
      {{- end }}
  replicas: {{ .Values.runtime.computeReplicas }}
{{- $clustername := .Values.clusterName }}
{{- range $addCompute := .Values.runtime.additionalCompute }}
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ $clustername }}-worker-{{ $addCompute.id }}
  namespace: {{ $clustername }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  clusterDeploymentRef:
    name: {{ $clustername }}
  name: worker-{{ $addCompute.id }}
  platform:
    azure:
      osDisk:
        diskSizeGB: {{ $addCompute.osDiskSizeGB }}
      type: {{ $addCompute.size }}
      zones:
      {{- range $addCompute.zones }}
      - '{{ . }}'
      {{- end }}
  replicas: {{ $addCompute.replicas }}
{{- end }}
