apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Azure
    region: {{ .Values.region }}
    name: {{ .Values.clusterName }}
    vendor: OpenShift
    versedt.dev/acm-enabled: 'true'
    versedt.dev/environment: lab
    cluster.open-cluster-management.io/clusterset: 'default'
  name: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  hubAcceptsClient: true