apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    region: {{ .Values.region }}
    cluster.open-cluster-management.io/clusterset: 'default'
    versedt.dev/acm-enabled: 'true'
    versedt.dev/environment: lab
  name: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
