apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
  {{- range $name, $value := .Values.runtime.managedClusterLabels }}
    {{ $name }}: '{{ $value }}'
  {{- end }}
    region: '{{ .Values.install.region }}'
  name: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
