apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: {{ .Values.clusterName }}
    baseDomain: {{ .Values.install.baseDomain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: {{ .Values.install.controlplaneReplicas }}
      platform:
        azure:
          osDisk:
            diskSizeGB: 128
          type:  Standard_D4s_v3
    compute:
    - hyperthreading: Enabled
      name: 'worker'
      replicas: {{ .Values.install.computeReplicas }}
      platform:
        azure:
          type:  Standard_D2s_v3
          osDisk:
            diskSizeGB: 128
          zones:
          - "1"
          - "2"
          - "3"
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      azure:
        baseDomainResourceGroupName: {{ .Values.install.resourcegroup }}
        cloudName: AzurePublicCloud
        region: {{ .Values.install.region }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
        {{ .Values.install.sshPubkey }}
