apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: {{ .Values.clusterName }}
    baseDomain: {{ .Values.install.baseDomain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: {{ .Values.install.controlPlaneReplicas }}
      platform:
        azure:
          osDisk:
            diskSizeGB: {{ .Values.install.controlPlane.osDiskSizeGB }}
          type: {{ .Values.install.controlPlane.size }}
    compute:
    - hyperthreading: Enabled
      name: 'worker'
      replicas: {{ .Values.install.computeReplicas }}
      platform:
        azure:
          type: {{ .Values.install.compute.size }}
          osDisk:
            diskSizeGB: {{ .Values.install.compute.osDiskSizeGB }}
          zones:
          {{- range .Values.install.compute.zones }}
          - '{{ . }}'
          {{- end }}
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      azure:
        baseDomainResourceGroupName: {{ .Values.install.resourceGroup }}
        cloudName: AzurePublicCloud
        region: {{ .Values.install.region }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
        {{ .Values.install.sshPubkey }}
