---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: pm-betacorp
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: versedt.dev/acm-enabled, operator: In, values: ["true"]}
          - {key: versedt.dev/environment, operator: In, values: ["lab"]}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: pb-betacorp
placementRef:
  name: pm-betacorp
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: pls-clusterconfig-betacorp
  apiGroup: policy.open-cluster-management.io
  kind: PolicySet
