apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-ocp-import-managed-cluster
  annotations:
    policy.open-cluster-management.io/description: 'Import a cluster to ACM Hub'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: setup-auto-importy
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: import-cluster-01   #cluster name to import
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: auto-import-secret
                namespace: import-cluster-01  #cluster name to import
              stringData:
                autoImportRetry: 10
                kubeconfig: {{ fromSecret "openshift-config" "import-cluster-01" "kubeconfig" }}
              type: Opaque
          - complianceType: musthave
            objectDefinition:             
              apiVersion: cluster.open-cluster-management.io/v1
              kind: ManagedCluster
              metadata:
                labels:
                  cloud: auto-detect
                  vendor: auto-detect
                name: import-cluster-01
              spec:
                hubAcceptsClient: true
                leaseDurationSeconds: 60            
          - complianceType: musthave
            objectDefinition:   
              apiVersion: agent.open-cluster-management.io/v1
              kind: KlusterletAddonConfig
              metadata:
                name: import-cluster-01
                namespace: import-cluster-01
              spec:
                clusterName: import-cluster-01
                clusterNamespace: import-cluster-01
                clusterLabels:
                  cloud: auto-detect
                  vendor: auto-detect
                applicationManager:
                  enabled: true
                  argocdCluster: true
                policyController:
                  enabled: true
                searchCollector:
                  enabled: true
                certPolicyController:
                  enabled: true
                iamPolicyController:
                  enabled: true                            
