apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-simple-cm
  annotations:
    policy.open-cluster-management.io/description: 'Create a simple ConfigMap'
    policy.open-cluster-management.io/standards: ''
    policy.open-cluster-management.io/categories: ''
    policy.open-cluster-management.io/controls: ''
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: simple-cm
        spec:
          remediationAction: inform
          severity: low
          pruneObjectBehavior: DeleteAll
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: test-simple-cm
                namespace: default
              data:
                clusterset: alphacorp
              immutable: false

