apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
  labels:
    cloud: 'vSphere'
    vendor: OpenShift
  annotations:
    argocd.argoproj.io/sync-options: Delete=true  
spec:
  baseDomain:  {{ .Values.install.baseDomain }}
  clusterName: {{ .Values.clusterName }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 3
  platform:
    vsphere:
      cluster: Cluster-1
      certificatesSecretRef:
        name: {{ .Values.clusterName }}-vsphere-certs
      credentialsSecretRef:
        name: {{ .Values.clusterName }}-vsphere-creds
      vCenter: {{ .Values.install.vsphere.vCenter }}
      datacenter: {{ .Values.install.vsphere.datacenter }}
      defaultDatastore: {{ .Values.install.vsphere.datastore }}
      network: {{ .Values.install.vsphere.network }}
      folder: {{ .Values.install.vsphere.folder }}
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.clusterName }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.clusterName }}-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.12.39-multi
      name: img{{ .Values.install.ocpVersion }}-multi-appsub
  pullSecretRef:
    name: {{ .Values.clusterName }}-pull-secret
