apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.clusterName }}-worker
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  clusterDeploymentRef:
    name: {{ .Values.clusterName }}
  name: worker
  platform:
    vsphere:
      cpus: {{ .Values.runtime.compute.cpus }}
      coresPerSocket: {{ .Values.runtime.compute.coresPerSocket }}
      memoryMB: {{ .Values.runtime.compute.memoryMB }}
      osDisk:
        diskSizeGB: {{ .Values.runtime.compute.osDiskSizeGB }}
  replicas: {{ .Values.runtime.computeReplicas }}
