apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: {{ .Values.clusterName }}  
    baseDomain: {{ .Values.install.baseDomain }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: {{ .Values.install.controlplaneReplicas }}
      platform:
        vsphere:
          cpus: {{ .Values.install.controlPlane.cpus }}
          coresPerSocket: {{ .Values.install.controlPlane.coresPerSocket }}
          memoryMB: {{ .Values.install.controlPlane.memoryMB }}
          osDisk:
            diskSizeGB: {{ .Values.install.controlPlane.osDiskSizeGB }}
    compute:
    - hyperthreading: Enabled
      name: 'worker'
      replicas: {{ .Values.install.computeReplicas }}
      platform:
        vsphere:
          cpus: {{ .Values.install.compute.cpus }}
          coresPerSocket: {{ .Values.install.compute.coresPerSocket }}
          memoryMB: {{ .Values.install.compute.memoryMB }}
          osDisk:
            diskSizeGB: {{ .Values.install.compute.osDiskSizeGB }}
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: {{ .Values.install.machineNetworkCIDR }}
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      vsphere:
        vCenter: {{ .Values.install.vsphere.vCenter }}
        username: {{ .Values.install.vsphere.username }}
        password: {{ .Values.install.vsphere.password }}
        datacenter: {{ .Values.install.vsphere.datacenter }}
        defaultDatastore: {{ .Values.install.vsphere.datastore }}
        cluster: {{ .Values.install.vsphere.cluster }}
        apiVIP: {{ .Values.install.vsphere.apiVIP }}
        ingressVIP: {{ .Values.install.vsphere.ingressVIP }}
        network: {{ .Values.install.vsphere.network }}
        folder:  {{ .Values.install.vsphere.folder }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey:  {{ .Values.install.sshPubkey }}
